version: '3'

services:
  api:
    restart: always
    build:
      context: ./src/api
      dockerfile: Dockerfile
    container_name: eatsomething-api
    ports:
      - 5000:5000
    volumes:
      - ./src/api/src:/srv/src/api/src
      - ./src/api/Cargo.toml:/srv/src/api/Cargo.toml
    environment:
      - DATABASE_URL=postgres://wombat:1wombat2@postgres:5432/eatsomething
      - RUST_BACKTRACE=1
      - RUST_LOG=info
      - JWT_SECRET=foofrah
    entrypoint: /srv/src/api/entrypoint.sh
    depends_on:
      - postgres

  ui:
    build:
      context: ./src/ui
      dockerfile: Dockerfile
    container_name: eatsomething-ui
    ports:
      - 3000:3000
    volumes:
      - ./src/:/srv/src/
    entrypoint: /srv/src/ui/entrypoint.sh

  postgres:
    image: postgres:11
    #    restart: always
    container_name: postgres
    environment:
      - POSTGRES_DB=eatsomething
      - POSTGRES_USER=wombat
      - POSTGRES_PASSWORD=1wombat2
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - ./data/postgres:/var/lib/postgresql/data/pgdata
    ports:
      - 5433:5432