indent_style = "Block"
reorder_imports = true
array_width = 100
attr_fn_like_width = 100
chain_width = 100
comment_width = 100
enum_discrim_align_threshold = 20
fn_call_width = 100
group_imports = "StdExternalCrate"
imports_granularity = "Crate"
inline_attribute_width = 100
struct_lit_width = 70
struct_variant_width = 80
max_width = 140
